[project]
name = "kaggle-introverts-extroverts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "jupyter>=1.1.1",
    "lab>=8.4",
    "pandas>=2.3.1",
    "plotly[express]>=6.2.0",
]
